name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Setup Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v3

      - name: "Verify diff between identical projects"
        run: ./test.sh

      - name: "Verify diff between identical projects"
        if: failure()
        run: cat App1/mylibrary/build/intermediates/compiled_local_resources/debug/compileDebugLibraryResources/out/layout_activity_main2.xml.flat